from .alexnet_ecoset import Alexnet_ecoset
from .barlowtwins_rn50 import BarlowTwins
from .resnet50_ecoset import Resnet50_ecoset
from .swav_rn50 import Swav
from .vicreg_rn50 import Vicreg
from .vgg16_ecoset import VGG16_ecoset
from .openclip import OpenCLIP
from .inception_ecoset import Inception_ecoset
from .official_clip import clip
